services:
  - type: web
    name: sparkvibe-ai
    env: python
    plan: free
    pythonVersion: "3.9"
    buildCommand: |
      apt-get update && apt-get install -y python3-dev build-essential
      python -m pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
    startCommand: "gunicorn -w 4 -b 0.0.0.0:$PORT server:app"
